/**
 * Buddy Planner - PDF Export
 *
 * Branded PDF generation with:
 * - Title block (logo, project name, date, scale)
 * - Floor plan page (canvas rasterized to PNG)
 * - BOQ page (table of workspace elements)
 */

export interface PdfExportOptions {
  projectName: string;
  date?: string;
  scale?: string;
  logoUrl?: string;
  floorPlanImage: string; // base64 PNG data URL
  boqItems: BoqItem[];
  companyName?: string;
}

export interface BoqItem {
  type: string;
  name: string;
  quantity: number;
  widthMm: number;
  heightMm: number;
  seatCount?: number;
  zone?: string;
  team?: string;
}

/**
 * Generate PDF using jsPDF.
 * Returns a Blob for download.
 */
export async function generateBuddyPdf(options: PdfExportOptions): Promise<Blob> {
  // Dynamic import to keep bundle size small
  const { default: jsPDF } = await import("jspdf");

  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;

  // ─── Page 1: Floor Plan ─────────────────────────────────────────────────

  // Title block
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(options.projectName || "Workspace Plan", margin, margin + 5);

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100);
  const dateStr = options.date || new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  pdf.text(`Date: ${dateStr}`, margin, margin + 12);
  pdf.text(`Scale: ${options.scale || "1:100"}`, margin + 60, margin + 12);
  if (options.companyName) {
    pdf.text(options.companyName, pageWidth - margin, margin + 5, { align: "right" });
  }

  // Divider line
  pdf.setDrawColor(200, 169, 110); // brand gold
  pdf.setLineWidth(0.5);
  pdf.line(margin, margin + 16, pageWidth - margin, margin + 16);

  // Floor plan image
  if (options.floorPlanImage) {
    const imgY = margin + 22;
    const imgMaxWidth = pageWidth - margin * 2;
    const imgMaxHeight = pageHeight - imgY - margin - 10;

    pdf.addImage(
      options.floorPlanImage,
      "PNG",
      margin,
      imgY,
      imgMaxWidth,
      imgMaxHeight,
      undefined,
      "FAST",
    );
  }

  // Footer
  pdf.setFontSize(7);
  pdf.setTextColor(150);
  pdf.text("Generated by Buddy Planner — oando.co.in", margin, pageHeight - 5);
  pdf.text(`Page 1 of 2`, pageWidth - margin, pageHeight - 5, { align: "right" });

  // ─── Page 2: Bill of Quantities ─────────────────────────────────────────

  pdf.addPage();
  pdf.setTextColor(0);
  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text("Bill of Quantities", margin, margin + 5);

  pdf.setDrawColor(200, 169, 110);
  pdf.setLineWidth(0.5);
  pdf.line(margin, margin + 10, pageWidth - margin, margin + 10);

  // Table header
  const tableY = margin + 18;
  const colWidths = [50, 40, 20, 30, 30, 30, 40, 40];
  const headers = ["Name", "Type", "Qty", "Width", "Height", "Seats", "Zone", "Team"];

  pdf.setFontSize(8);
  pdf.setFont("helvetica", "bold");
  let x = margin;
  for (let i = 0; i < headers.length; i++) {
    pdf.text(headers[i], x, tableY);
    x += colWidths[i];
  }

  // Table rows
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(7);
  let y = tableY + 6;

  for (const item of options.boqItems) {
    if (y > pageHeight - margin - 10) {
      pdf.addPage();
      y = margin + 10;
    }

    x = margin;
    const row = [
      item.name,
      item.type,
      String(item.quantity),
      `${item.widthMm}mm`,
      `${item.heightMm}mm`,
      item.seatCount ? String(item.seatCount) : "-",
      item.zone || "-",
      item.team || "-",
    ];

    for (let i = 0; i < row.length; i++) {
      pdf.text(row[i], x, y);
      x += colWidths[i];
    }
    y += 5;
  }

  // Summary
  y += 5;
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(9);
  const totalSeats = options.boqItems.reduce((sum, item) => sum + (item.seatCount || 0) * item.quantity, 0);
  const totalItems = options.boqItems.reduce((sum, item) => sum + item.quantity, 0);
  pdf.text(`Total Elements: ${totalItems}  |  Total Seats: ${totalSeats}`, margin, y);

  // Footer
  pdf.setFontSize(7);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(150);
  pdf.text("Generated by Buddy Planner — oando.co.in", margin, pageHeight - 5);
  pdf.text(`Page 2 of 2`, pageWidth - margin, pageHeight - 5, { align: "right" });

  return pdf.output("blob");
}

/**
 * Trigger PDF download in browser.
 */
export async function downloadBuddyPdf(options: PdfExportOptions): Promise<void> {
  const blob = await generateBuddyPdf(options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${options.projectName || "workspace-plan"}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Escape a string for safe CSV output (prevent formula injection). */
function csvEscape(value: string): string {
  // Escape embedded double quotes
  let escaped = value.replace(/"/g, '""');
  // Prefix formula-triggering characters to prevent Excel formula injection
  if (/^[=+\-@\t\r]/.test(escaped)) {
    escaped = `'${escaped}`;
  }
  return `"${escaped}"`;
}

/**
 * Export to CSV (BOQ data).
 */
export function downloadBoqCsv(items: BoqItem[], projectName: string): void {
  const headers = "Name,Type,Quantity,Width (mm),Height (mm),Seats,Zone,Team\n";
  const rows = items.map((item) =>
    [
      csvEscape(item.name),
      csvEscape(item.type),
      item.quantity,
      item.widthMm,
      item.heightMm,
      item.seatCount || "",
      csvEscape(item.zone || ""),
      csvEscape(item.team || ""),
    ].join(",")
  ).join("\n");

  const csv = headers + rows;
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName || "workspace"}-boq.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
