/**
 * OOFPL Furniture Catalog Data
 *
 * Each item includes SVG icon path, SKU, real-world dimensions (mm),
 * category, and price in INR (default 0).
 */

import {
  getCatalogItemById as getCatalogItemByIdFromCatalog,
  matchesCatalogSearch as matchesCatalogSearchInCatalog,
  rankCatalogReplacementOptions as rankCatalogReplacementOptionsInCatalog,
} from "./catalogHelpers";

export type FurnitureCategory =
  | "seating"
  | "desks"
  | "tables"
  | "storage"
  | "soft-seating"
  | "education"
  | "misc";

export type FurnitureShape =
  | "workstation-linear" | "workstation-l" | "workstation-cluster" | "workstation-bench"
  | "task-chair" | "executive-chair" | "visitor-chair" | "stool" | "ergonomic-chair"
  | "meeting-table-4" | "meeting-table-6" | "conference-table-10" | "cafeteria-table"
  | "pedestal" | "filing-cabinet" | "bookshelf" | "locker" | "credenza" | "storage-wall"
  | "sofa-2seat" | "lounge-chair" | "ottoman" | "sofa-3seat"
  | "screen-divider" | "whiteboard" | "planter" | "desk-lamp" | "monitor-arm" | "cable-tray"
  | "reception-desk" | "standing-desk" | "phone-booth" | "coat-stand"
  | "desk" | "desk-l" | "office-chair" | "dining-table-rect" | "dining-chair"
  | "meeting-pod" | "partition-screen" | "locker-unit" | "round-table";

export interface CatalogItem {
  id: string;
  name: string;
  sku: string;
  category: FurnitureCategory;
  widthMm: number;
  depthMm: number;
  heightMm: number;
  iconPath: string;
  priceInr: number;
  /** Legacy shape identifier used by the placement system */
  shape: FurnitureShape;
}

export const furnitureCatalog: CatalogItem[] = [
  // ─── DESKS ────────────────────────────────────────────────────────
  {
    id: "ws-linear-120",
    name: "Linear Desk 1200",
    sku: "OOFPL-DSK-001",
    category: "desks",
    widthMm: 1200,
    depthMm: 600,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-linear-120.svg",
    priceInr: 0,
    shape: "workstation-linear",
  },
  {
    id: "ws-linear-140",
    name: "Linear Desk 1400",
    sku: "OOFPL-DSK-002",
    category: "desks",
    widthMm: 1400,
    depthMm: 700,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-linear-140.svg",
    priceInr: 0,
    shape: "workstation-linear",
  },
  {
    id: "ws-linear-160",
    name: "Linear Desk 1600",
    sku: "OOFPL-DSK-003",
    category: "desks",
    widthMm: 1600,
    depthMm: 800,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-linear-160.svg",
    priceInr: 0,
    shape: "workstation-linear",
  },
  {
    id: "ws-l-shape",
    name: "L-Shaped Workstation",
    sku: "OOFPL-DSK-004",
    category: "desks",
    widthMm: 1600,
    depthMm: 1400,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-l-shape.svg",
    priceInr: 0,
    shape: "workstation-l",
  },
  {
    id: "ws-cluster-4",
    name: "4-Person Cluster",
    sku: "OOFPL-DSK-005",
    category: "desks",
    widthMm: 2400,
    depthMm: 1400,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-cluster-4.svg",
    priceInr: 0,
    shape: "workstation-cluster",
  },
  {
    id: "ws-bench-2",
    name: "Bench Desk (2-Person)",
    sku: "OOFPL-DSK-006",
    category: "desks",
    widthMm: 2400,
    depthMm: 700,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-bench-2.svg",
    priceInr: 0,
    shape: "workstation-bench",
  },
  {
    id: "ws-bench-4",
    name: "Bench Desk (4-Person)",
    sku: "OOFPL-DSK-007",
    category: "desks",
    widthMm: 4800,
    depthMm: 700,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/ws-bench-4.svg",
    priceInr: 0,
    shape: "workstation-bench",
  },
  {
    id: "standing-desk",
    name: "Standing Desk",
    sku: "OOFPL-DSK-008",
    category: "desks",
    widthMm: 1400,
    depthMm: 700,
    heightMm: 1100,
    iconPath: "/furniture-icons/desks/standing-desk.svg",
    priceInr: 0,
    shape: "standing-desk",
  },
  {
    id: "exec-desk",
    name: "Executive Desk",
    sku: "OOFPL-DSK-009",
    category: "desks",
    widthMm: 1800,
    depthMm: 800,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/exec-desk.svg",
    priceInr: 0,
    shape: "workstation-linear",
  },
  {
    id: "reception-desk",
    name: "Reception Desk",
    sku: "OOFPL-DSK-010",
    category: "desks",
    widthMm: 2000,
    depthMm: 800,
    heightMm: 1100,
    iconPath: "/furniture-icons/desks/reception-desk.svg",
    priceInr: 0,
    shape: "reception-desk",
  },
  {
    id: "l-desk",
    name: "L-Desk",
    sku: "OOFPL-DSK-011",
    category: "desks",
    widthMm: 1600,
    depthMm: 1400,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/l-desk.svg",
    priceInr: 0,
    shape: "desk-l",
  },
  {
    id: "workstation-desk",
    name: "Workstation",
    sku: "OOFPL-DSK-012",
    category: "desks",
    widthMm: 1400,
    depthMm: 700,
    heightMm: 750,
    iconPath: "/furniture-icons/desks/workstation-desk.svg",
    priceInr: 0,
    shape: "workstation-linear",
  },

  // ─── SEATING ──────────────────────────────────────────────────────
  {
    id: "task-chair",
    name: "Task Chair",
    sku: "OOFPL-SEA-001",
    category: "seating",
    widthMm: 500,
    depthMm: 500,
    heightMm: 900,
    iconPath: "/furniture-icons/chairs/task-chair.svg",
    priceInr: 0,
    shape: "task-chair",
  },
  {
    id: "task-chair-arms",
    name: "Task Chair (with Arms)",
    sku: "OOFPL-SEA-002",
    category: "seating",
    widthMm: 550,
    depthMm: 550,
    heightMm: 950,
    iconPath: "/furniture-icons/chairs/task-chair-arms.svg",
    priceInr: 0,
    shape: "task-chair",
  },
  {
    id: "executive-chair",
    name: "Executive Chair",
    sku: "OOFPL-SEA-003",
    category: "seating",
    widthMm: 650,
    depthMm: 650,
    heightMm: 1200,
    iconPath: "/furniture-icons/chairs/executive-chair.svg",
    priceInr: 0,
    shape: "executive-chair",
  },
  {
    id: "ergonomic-chair",
    name: "Ergonomic Chair",
    sku: "OOFPL-SEA-004",
    category: "seating",
    widthMm: 600,
    depthMm: 600,
    heightMm: 1100,
    iconPath: "/furniture-icons/chairs/ergonomic-chair.svg",
    priceInr: 0,
    shape: "ergonomic-chair",
  },
  {
    id: "visitor-chair",
    name: "Visitor Chair",
    sku: "OOFPL-SEA-005",
    category: "seating",
    widthMm: 500,
    depthMm: 500,
    heightMm: 850,
    iconPath: "/furniture-icons/chairs/visitor-chair.svg",
    priceInr: 0,
    shape: "visitor-chair",
  },
  {
    id: "visitor-chair-arms",
    name: "Visitor Chair (Arms)",
    sku: "OOFPL-SEA-006",
    category: "seating",
    widthMm: 550,
    depthMm: 550,
    heightMm: 850,
    iconPath: "/furniture-icons/chairs/visitor-chair-arms.svg",
    priceInr: 0,
    shape: "visitor-chair",
  },
  {
    id: "stacking-chair",
    name: "Stacking Chair",
    sku: "OOFPL-SEA-007",
    category: "seating",
    widthMm: 450,
    depthMm: 450,
    heightMm: 800,
    iconPath: "/furniture-icons/chairs/stacking-chair.svg",
    priceInr: 0,
    shape: "visitor-chair",
  },
  {
    id: "bar-stool",
    name: "Bar Stool",
    sku: "OOFPL-SEA-008",
    category: "seating",
    widthMm: 400,
    depthMm: 400,
    heightMm: 750,
    iconPath: "/furniture-icons/chairs/bar-stool.svg",
    priceInr: 0,
    shape: "stool",
  },
  {
    id: "drafting-stool",
    name: "Drafting Stool",
    sku: "OOFPL-SEA-009",
    category: "seating",
    widthMm: 450,
    depthMm: 450,
    heightMm: 700,
    iconPath: "/furniture-icons/chairs/drafting-stool.svg",
    priceInr: 0,
    shape: "stool",
  },

  // ─── TABLES ───────────────────────────────────────────────────────
  {
    id: "meeting-4",
    name: "Meeting Table (4-Seat)",
    sku: "OOFPL-TBL-001",
    category: "tables",
    widthMm: 1200,
    depthMm: 800,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/meeting-4.svg",
    priceInr: 0,
    shape: "meeting-table-4",
  },
  {
    id: "meeting-6",
    name: "Meeting Table (6-Seat)",
    sku: "OOFPL-TBL-002",
    category: "tables",
    widthMm: 1800,
    depthMm: 900,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/meeting-6.svg",
    priceInr: 0,
    shape: "meeting-table-6",
  },
  {
    id: "conference-10",
    name: "Conference Table (10-Seat)",
    sku: "OOFPL-TBL-003",
    category: "tables",
    widthMm: 3000,
    depthMm: 1200,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/conference-10.svg",
    priceInr: 0,
    shape: "conference-table-10",
  },
  {
    id: "conference-8",
    name: "Conference Table (8-Seat)",
    sku: "OOFPL-TBL-004",
    category: "tables",
    widthMm: 2400,
    depthMm: 1100,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/conference-8.svg",
    priceInr: 0,
    shape: "conference-table-10",
  },
  {
    id: "cafeteria-round",
    name: "Cafeteria Table (Round)",
    sku: "OOFPL-TBL-005",
    category: "tables",
    widthMm: 800,
    depthMm: 800,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/cafeteria-round.svg",
    priceInr: 0,
    shape: "cafeteria-table",
  },
  {
    id: "cafeteria-rect",
    name: "Cafeteria Table (Rect)",
    sku: "OOFPL-TBL-006",
    category: "tables",
    widthMm: 1200,
    depthMm: 600,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/cafeteria-rect.svg",
    priceInr: 0,
    shape: "dining-table-rect",
  },
  {
    id: "standing-meeting",
    name: "Standing Meeting Table",
    sku: "OOFPL-TBL-007",
    category: "tables",
    widthMm: 1000,
    depthMm: 600,
    heightMm: 1050,
    iconPath: "/furniture-icons/tables/standing-meeting.svg",
    priceInr: 0,
    shape: "meeting-table-4",
  },
  {
    id: "round-table",
    name: "Round Table",
    sku: "OOFPL-TBL-008",
    category: "tables",
    widthMm: 1000,
    depthMm: 1000,
    heightMm: 750,
    iconPath: "/furniture-icons/tables/round-table.svg",
    priceInr: 0,
    shape: "round-table",
  },

  // ─── STORAGE ──────────────────────────────────────────────────────
  {
    id: "pedestal-2",
    name: "2-Drawer Pedestal",
    sku: "OOFPL-STR-001",
    category: "storage",
    widthMm: 400,
    depthMm: 500,
    heightMm: 600,
    iconPath: "/furniture-icons/storage/pedestal-2.svg",
    priceInr: 0,
    shape: "pedestal",
  },
  {
    id: "pedestal-3",
    name: "3-Drawer Pedestal",
    sku: "OOFPL-STR-002",
    category: "storage",
    widthMm: 400,
    depthMm: 600,
    heightMm: 650,
    iconPath: "/furniture-icons/storage/pedestal-3.svg",
    priceInr: 0,
    shape: "pedestal",
  },
  {
    id: "filing-2",
    name: "Filing Cabinet (2-Drawer)",
    sku: "OOFPL-STR-003",
    category: "storage",
    widthMm: 450,
    depthMm: 620,
    heightMm: 700,
    iconPath: "/furniture-icons/storage/filing-2.svg",
    priceInr: 0,
    shape: "filing-cabinet",
  },
  {
    id: "filing-4",
    name: "Filing Cabinet (4-Drawer)",
    sku: "OOFPL-STR-004",
    category: "storage",
    widthMm: 450,
    depthMm: 620,
    heightMm: 1300,
    iconPath: "/furniture-icons/storage/filing-4.svg",
    priceInr: 0,
    shape: "filing-cabinet",
  },
  {
    id: "lateral-file",
    name: "Lateral File Cabinet",
    sku: "OOFPL-STR-005",
    category: "storage",
    widthMm: 800,
    depthMm: 450,
    heightMm: 700,
    iconPath: "/furniture-icons/storage/lateral-file.svg",
    priceInr: 0,
    shape: "filing-cabinet",
  },
  {
    id: "bookshelf-low",
    name: "Low Bookshelf",
    sku: "OOFPL-STR-006",
    category: "storage",
    widthMm: 800,
    depthMm: 300,
    heightMm: 900,
    iconPath: "/furniture-icons/storage/bookshelf-low.svg",
    priceInr: 0,
    shape: "bookshelf",
  },
  {
    id: "bookshelf-tall",
    name: "Tall Bookshelf",
    sku: "OOFPL-STR-007",
    category: "storage",
    widthMm: 800,
    depthMm: 350,
    heightMm: 1800,
    iconPath: "/furniture-icons/storage/bookshelf-tall.svg",
    priceInr: 0,
    shape: "bookshelf",
  },
  {
    id: "locker-single",
    name: "Locker (Single)",
    sku: "OOFPL-STR-008",
    category: "storage",
    widthMm: 300,
    depthMm: 450,
    heightMm: 1800,
    iconPath: "/furniture-icons/storage/locker-single.svg",
    priceInr: 0,
    shape: "locker",
  },
  {
    id: "locker-bank-4",
    name: "Locker Bank (4-wide)",
    sku: "OOFPL-STR-009",
    category: "storage",
    widthMm: 1200,
    depthMm: 450,
    heightMm: 1800,
    iconPath: "/furniture-icons/storage/locker-bank-4.svg",
    priceInr: 0,
    shape: "locker",
  },
  {
    id: "locker-unit",
    name: "Locker Unit (6-wide)",
    sku: "OOFPL-STR-010",
    category: "storage",
    widthMm: 1600,
    depthMm: 450,
    heightMm: 1800,
    iconPath: "/furniture-icons/storage/locker-unit.svg",
    priceInr: 0,
    shape: "locker-unit",
  },
  {
    id: "credenza",
    name: "Credenza",
    sku: "OOFPL-STR-011",
    category: "storage",
    widthMm: 1200,
    depthMm: 450,
    heightMm: 750,
    iconPath: "/furniture-icons/storage/credenza.svg",
    priceInr: 0,
    shape: "credenza",
  },
  {
    id: "storage-wall",
    name: "Storage Wall Unit",
    sku: "OOFPL-STR-012",
    category: "storage",
    widthMm: 1600,
    depthMm: 400,
    heightMm: 2000,
    iconPath: "/furniture-icons/storage/storage-wall.svg",
    priceInr: 0,
    shape: "storage-wall",
  },

  // ─── SOFT SEATING ─────────────────────────────────────────────────
  {
    id: "sofa-2",
    name: "2-Seat Sofa",
    sku: "OOFPL-SFT-001",
    category: "soft-seating",
    widthMm: 1400,
    depthMm: 700,
    heightMm: 850,
    iconPath: "/furniture-icons/sofas/sofa-2.svg",
    priceInr: 0,
    shape: "sofa-2seat",
  },
  {
    id: "sofa-3",
    name: "3-Seat Sofa",
    sku: "OOFPL-SFT-002",
    category: "soft-seating",
    widthMm: 2000,
    depthMm: 800,
    heightMm: 850,
    iconPath: "/furniture-icons/sofas/sofa-3.svg",
    priceInr: 0,
    shape: "sofa-3seat",
  },
  {
    id: "lounge-chair",
    name: "Lounge Chair",
    sku: "OOFPL-SFT-003",
    category: "soft-seating",
    widthMm: 700,
    depthMm: 700,
    heightMm: 800,
    iconPath: "/furniture-icons/sofas/lounge-chair.svg",
    priceInr: 0,
    shape: "lounge-chair",
  },
  {
    id: "tub-chair",
    name: "Tub Chair",
    sku: "OOFPL-SFT-004",
    category: "soft-seating",
    widthMm: 650,
    depthMm: 650,
    heightMm: 750,
    iconPath: "/furniture-icons/sofas/tub-chair.svg",
    priceInr: 0,
    shape: "lounge-chair",
  },
  {
    id: "ottoman",
    name: "Ottoman",
    sku: "OOFPL-SFT-005",
    category: "soft-seating",
    widthMm: 500,
    depthMm: 500,
    heightMm: 400,
    iconPath: "/furniture-icons/sofas/ottoman.svg",
    priceInr: 0,
    shape: "ottoman",
  },
  {
    id: "bench-seat",
    name: "Bench Seat",
    sku: "OOFPL-SFT-006",
    category: "soft-seating",
    widthMm: 1200,
    depthMm: 400,
    heightMm: 450,
    iconPath: "/furniture-icons/sofas/bench-seat.svg",
    priceInr: 0,
    shape: "sofa-2seat",
  },

  // ─── MISC ─────────────────────────────────────────────────────────
  {
    id: "screen-120",
    name: "Screen Divider 1200",
    sku: "OOFPL-MSC-001",
    category: "misc",
    widthMm: 1200,
    depthMm: 40,
    heightMm: 1400,
    iconPath: "/furniture-icons/misc/screen-120.svg",
    priceInr: 0,
    shape: "screen-divider",
  },
  {
    id: "screen-160",
    name: "Screen Divider 1600",
    sku: "OOFPL-MSC-002",
    category: "misc",
    widthMm: 1600,
    depthMm: 40,
    heightMm: 1400,
    iconPath: "/furniture-icons/misc/screen-160.svg",
    priceInr: 0,
    shape: "screen-divider",
  },
  {
    id: "partition-screen",
    name: "Partition Screen",
    sku: "OOFPL-MSC-003",
    category: "misc",
    widthMm: 1200,
    depthMm: 60,
    heightMm: 1600,
    iconPath: "/furniture-icons/misc/partition-screen.svg",
    priceInr: 0,
    shape: "partition-screen",
  },
  {
    id: "whiteboard",
    name: "Whiteboard",
    sku: "OOFPL-MSC-004",
    category: "misc",
    widthMm: 1200,
    depthMm: 60,
    heightMm: 900,
    iconPath: "/furniture-icons/misc/whiteboard.svg",
    priceInr: 0,
    shape: "whiteboard",
  },
  {
    id: "whiteboard-mobile",
    name: "Mobile Whiteboard",
    sku: "OOFPL-MSC-005",
    category: "misc",
    widthMm: 1000,
    depthMm: 80,
    heightMm: 1800,
    iconPath: "/furniture-icons/misc/whiteboard-mobile.svg",
    priceInr: 0,
    shape: "whiteboard",
  },
  {
    id: "planter-rect",
    name: "Planter Box",
    sku: "OOFPL-MSC-006",
    category: "misc",
    widthMm: 600,
    depthMm: 200,
    heightMm: 800,
    iconPath: "/furniture-icons/misc/planter-rect.svg",
    priceInr: 0,
    shape: "planter",
  },
  {
    id: "planter-round",
    name: "Round Planter",
    sku: "OOFPL-MSC-007",
    category: "misc",
    widthMm: 300,
    depthMm: 300,
    heightMm: 700,
    iconPath: "/furniture-icons/misc/planter-round.svg",
    priceInr: 0,
    shape: "planter",
  },
  {
    id: "meeting-pod",
    name: "Meeting Pod",
    sku: "OOFPL-MSC-008",
    category: "misc",
    widthMm: 2000,
    depthMm: 2000,
    heightMm: 2200,
    iconPath: "/furniture-icons/misc/meeting-pod.svg",
    priceInr: 0,
    shape: "meeting-pod",
  },
  {
    id: "phone-booth",
    name: "Phone Booth",
    sku: "OOFPL-MSC-009",
    category: "misc",
    widthMm: 1000,
    depthMm: 1000,
    heightMm: 2200,
    iconPath: "/furniture-icons/misc/phone-booth.svg",
    priceInr: 0,
    shape: "phone-booth",
  },
  {
    id: "coat-stand",
    name: "Coat Stand",
    sku: "OOFPL-MSC-010",
    category: "misc",
    widthMm: 400,
    depthMm: 400,
    heightMm: 1700,
    iconPath: "/furniture-icons/misc/coat-stand.svg",
    priceInr: 0,
    shape: "coat-stand",
  },
  {
    id: "desk-lamp",
    name: "Desk Lamp",
    sku: "OOFPL-MSC-011",
    category: "misc",
    widthMm: 200,
    depthMm: 200,
    heightMm: 450,
    iconPath: "/furniture-icons/misc/desk-lamp.svg",
    priceInr: 0,
    shape: "desk-lamp",
  },
  {
    id: "cable-tray",
    name: "Cable Management Tray",
    sku: "OOFPL-MSC-012",
    category: "misc",
    widthMm: 600,
    depthMm: 100,
    heightMm: 80,
    iconPath: "/furniture-icons/misc/cable-tray.svg",
    priceInr: 0,
    shape: "cable-tray",
  },
  {
    id: "waste-bin",
    name: "Waste Bin",
    sku: "OOFPL-MSC-013",
    category: "misc",
    widthMm: 250,
    depthMm: 250,
    heightMm: 400,
    iconPath: "/furniture-icons/misc/waste-bin.svg",
    priceInr: 0,
    shape: "stool",
  },
];

/** All distinct categories present in the catalog */
export const categories: FurnitureCategory[] = [
  "desks",
  "seating",
  "tables",
  "storage",
  "soft-seating",
  "misc",
];

/** Category display labels */
export const categoryLabels: Record<FurnitureCategory, string> = {
  seating: "Seating",
  desks: "Desks",
  tables: "Tables",
  storage: "Storage",
  "soft-seating": "Soft Seating",
  education: "Education",
  misc: "Misc",
};

export function getCatalogItemById(id: string | null | undefined): CatalogItem | undefined {
  return getCatalogItemByIdFromCatalog(furnitureCatalog, id);
}

export function matchesCatalogSearch(item: CatalogItem, query: string): boolean {
  return matchesCatalogSearchInCatalog(item, query, categoryLabels);
}

export function rankCatalogReplacementOptions(
  currentItem: CatalogItem | undefined,
  query = "",
): CatalogItem[] {
  return rankCatalogReplacementOptionsInCatalog(
    furnitureCatalog,
    categoryLabels,
    currentItem,
    query
  );
}
